config/routes.rb
Rails.application.routes.draw do
  devise_for :users
resources:posts
resources:comments
  root "posts#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
      # return unless user.present?
      # can :read, :all
      # return unless user.admin?
      # can :manage, :all
      # user ||= User.new  # Handle the case where user is nil (not logged in)
      # if user.!present?
      #   can :read, Post
      # end
      # Abilities for all users
     
  
      if user.present?
        # Abilities for logged-in users
        if user.role == "user"
          can :edit, Post
        end
  
        if user.role == "admin"
          # Abilities for admin users
          can :update, Post
          can :edit, Post

          # Add other admin-specific abilities as needed
        end
      end
    
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
    has_many :posts
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :comments
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
   
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
    @comment = Comment.new
  end

  def create
    @comment = Comment.new(comment_params)
    
    if @comment.save
      redirect_to comments_path
    else
      render :new
    end
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    
    if @comment.update(comment_params)
      redirect_to posts_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    
    if @comment.destroy
      redirect_to comments_path
    else
      render :index
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:description, :a_blog_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
    def index
      @posts = Post.all
    end
  
    def show
      @post = Post.find(params[:id])
    end
  
    def new
      @post = Post.new
    end
  
    def create
     
      @post = Post.new(post_params)
  
      if @post.save
        redirect_to posts_path
      else
        render :new
      end
    end
  
    def edit
      @post = Post.find(params[:id])
    end
  
    def update
      @post = Post.find(params[:id])
  
      if @post.update(post_params)
        redirect_to posts_path
      else
        render :edit
      end
    end
  
    def destroy
      @post = Post.find(params[:id])
  
      if @post.destroy
        redirect_to posts_path
      else
        render :index
      end
    end
  
    private
  
    def post_params
      params.require(:post).permit(:title, :content, :author_id,:image)
    end
  end
  

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<h1>Edit Comment</h1>

<%= form_for @comment do |f| %>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <%= f.submit 'Update Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <!-- Add any other attributes you want to edit -->

  <div>
    <%= f.submit 'Update Post' %>
  </div>
<% end %>

<%= link_to 'Back to Posts', posts_path %>

app/views/posts/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Your Page Title</title>
  <style>
    body {
      display: flex;
      align-items: center;
      justify-content: center;
      height: 100vh;
      margin: 0;
    }

    #page-container {
      border: 2px solid #ccc;
      padding: 20px;
    }
  </style>
</head>
<body>
   
<div id="page-container">
  <h1>Posts</h1>

  <ul>
    <%= link_to 'New Post', new_post_path %>

    <% @posts.each do |post| %>
      <li>
        <%= post.title %><br>
        <% if post.image.present? %>
          <%= image_tag post.image, alt: 'Post Image', style: 'width: 200px; height: 200px;' %><br>
        <% end %>
        <%= post.content %><br>
        <%= link_to 'Edit', edit_post_path(post) %>

        <% post.comments.each do |comment| %>
          <h4>========comments=========</h4>
          <%= link_to 'Edit Comment', edit_comment_path(comment) %>
          <%= comment.description %><br>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>
<% if user_signed_in? %> 
<div> Welcome <%= current_user.email %> </div> 
 <%= button_to "Sign out", destroy_user_session_path, method: :delete %> 
<% else %>
 <%= button_to "Sign in", new_user_session_path %> 
<% end %>
</body>
</html>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= form_for @post do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :upload_Image %>
    <%= f.file_field :image %>
</div>
  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>
  <%= f.label :author_id %>
  <%= f.text_area :author_id %>
</div>
  <%= f.submit 'Create Post' %>
<% end %>

<%= link_to 'Back', posts_path %>